apiVersion: v1
kind: Pod
metadata:
  name: pa11y-dashboard
  labels:
    app: kaniko
    component: ci
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.3.0-debug
    command:
    - /busybox/cat
    tty: true
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 1250m
        memory: 2Gi
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: jenkins-ecr-credentials
          key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
    - mountPath: /kaniko/.docker
      name: kaniko-config-json
  volumes:
    - name: kaniko-config-json
      secret:
        secretName: kaniko-config-json
        items:
        - key: config.json
          path: config.json
